version: "3.8"
services:
  client:
    build:
      context: ./client
    environment:
      CLIENT_PORT: ${CLIENT_PORT}
    ports:
      - "3000:3000"

  api:
    build:
      context: ./api
    environment:
      NODE_ENV: production
      API_PORT: ${API_PORT}
      API_DB_HOST: ${API_DB_HOST}
      API_DB_PORT: ${API_DB_PORT}
      API_DB_USER_NAME: ${API_DB_USER_NAME}
      API_DB_PASSWORD: ${API_DB_PASSWORD}
      API_DB_DATABASE: ${API_DB_DATABASE}
    ports:
      - "4000:${API_PORT}"
    depends_on:
      database:
        condition: service_healthy
    links:
      - database

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"

  database:
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: ${API_DB_USER_NAME}
      POSTGRES_PASSWORD: ${API_DB_PASSWORD}
      POSTGRES_DB: ${API_DB_DATABASE}
    ports:
      - "5234:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  database-data:
