version: "3.8"
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"

  api:
    build:
      context: ./api
    ports:
      - "4000:4000"
    depends_on:
      database:
        condition: service_healthy
    links:
      - database

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"

  database:
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwe123ewq321
      POSTGRES_DB: imaginator
    ports:
      - "5234:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  database-data:
