version: "3.8"
services:
  server:
    build:
      context: ./server
    ports:
      - "4000:4000"

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"

  database:
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwe123ewq321
      POSTGRES_DB: imaginator
    ports:
      - "5234:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data:
