version: "3.1"
services:
  database:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwe123ewq321
      POSTGRES_DB: imaginator
    ports:
      - "5433:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data:
